/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Tour } from "./Tour";
import { TourCountArgs } from "./TourCountArgs";
import { TourFindManyArgs } from "./TourFindManyArgs";
import { TourFindUniqueArgs } from "./TourFindUniqueArgs";
import { CreateTourArgs } from "./CreateTourArgs";
import { UpdateTourArgs } from "./UpdateTourArgs";
import { DeleteTourArgs } from "./DeleteTourArgs";
import { BoatFindManyArgs } from "../../boat/base/BoatFindManyArgs";
import { Boat } from "../../boat/base/Boat";
import { PriceFindManyArgs } from "../../price/base/PriceFindManyArgs";
import { Price } from "../../price/base/Price";
import { ScheduleFindManyArgs } from "../../schedule/base/ScheduleFindManyArgs";
import { Schedule } from "../../schedule/base/Schedule";
import { TourService } from "../tour.service";
@graphql.Resolver(() => Tour)
export class TourResolverBase {
  constructor(protected readonly service: TourService) {}

  async _toursMeta(
    @graphql.Args() args: TourCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Tour])
  async tours(@graphql.Args() args: TourFindManyArgs): Promise<Tour[]> {
    return this.service.tours(args);
  }

  @graphql.Query(() => Tour, { nullable: true })
  async tour(@graphql.Args() args: TourFindUniqueArgs): Promise<Tour | null> {
    const result = await this.service.tour(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Tour)
  async createTour(@graphql.Args() args: CreateTourArgs): Promise<Tour> {
    return await this.service.createTour({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Tour)
  async updateTour(@graphql.Args() args: UpdateTourArgs): Promise<Tour | null> {
    try {
      return await this.service.updateTour({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Tour)
  async deleteTour(@graphql.Args() args: DeleteTourArgs): Promise<Tour | null> {
    try {
      return await this.service.deleteTour(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Boat], { name: "boats" })
  async findBoats(
    @graphql.Parent() parent: Tour,
    @graphql.Args() args: BoatFindManyArgs
  ): Promise<Boat[]> {
    const results = await this.service.findBoats(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Price], { name: "prices" })
  async findPrices(
    @graphql.Parent() parent: Tour,
    @graphql.Args() args: PriceFindManyArgs
  ): Promise<Price[]> {
    const results = await this.service.findPrices(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Schedule], { name: "schedules" })
  async findSchedules(
    @graphql.Parent() parent: Tour,
    @graphql.Args() args: ScheduleFindManyArgs
  ): Promise<Schedule[]> {
    const results = await this.service.findSchedules(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
