/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BoatListRelationFilter } from "../../boat/base/BoatListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { PriceListRelationFilter } from "../../price/base/PriceListRelationFilter";
import { ScheduleListRelationFilter } from "../../schedule/base/ScheduleListRelationFilter";

@InputType()
class TourWhereInput {
  @ApiProperty({
    required: false,
    type: () => BoatListRelationFilter,
  })
  @ValidateNested()
  @Type(() => BoatListRelationFilter)
  @IsOptional()
  @Field(() => BoatListRelationFilter, {
    nullable: true,
  })
  boats?: BoatListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  description?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => PriceListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PriceListRelationFilter)
  @IsOptional()
  @Field(() => PriceListRelationFilter, {
    nullable: true,
  })
  prices?: PriceListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ScheduleListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ScheduleListRelationFilter)
  @IsOptional()
  @Field(() => ScheduleListRelationFilter, {
    nullable: true,
  })
  schedules?: ScheduleListRelationFilter;
}

export { TourWhereInput as TourWhereInput };
